create table IF NOT EXISTS sys_user(
 id varchar(50) primary key,
 username varchar(50) not null,
 salt varchar(100) not null,
 password varchar(60) not null,
 phone varchar(50) not null,
 dept_id varchar(50) not null,
 dept_name varchar(50) not null,
 real_name varchar(50) not null,
 nick_name varchar(50) not null,
 email varchar(50) not null,
 status integer,
 sex integer,
 deleted integer,
 create_id varchar(50) not null,
 update_id varchar(50) not null,
 create_where integer,
 create_time timestamp not null,
 update_time timestamp not null
 );